-- MySQL schema for the host and every conference-tools package, mirroring the
-- Laravel migrations. No generator ships with the repo: keep this file in step
-- with the migrations by hand whenever one is added or changed.
-- Idempotent: every table uses CREATE TABLE IF NOT EXISTS and the
-- migration rows are inserted only when absent, so re-importing over an
-- existing database makes no changes and raises no errors.
-- Includes the `migrations` table and rows marking every migration as run
-- (batch 1), so a future `php artisan migrate` only applies NEW migrations.
SET FOREIGN_KEY_CHECKS=0;

CREATE TABLE IF NOT EXISTS `migrations` (`id` int unsigned not null auto_increment primary key, `migration` varchar(255) not null, `batch` int not null) default character set utf8mb4 collate 'utf8mb4_unicode_ci';
CREATE TABLE IF NOT EXISTS `users` (`id` bigint unsigned not null auto_increment primary key, `name` varchar(255) not null, `email` varchar(255) not null, `email_verified_at` timestamp null, `password` varchar(255) not null, `is_admin` tinyint(1) not null default '0', `is_locked` tinyint(1) not null default '0', `must_change_password` tinyint(1) not null default '0', `two_factor_secret` text null, `two_factor_recovery_codes` text null, `two_factor_confirmed_at` timestamp null, `remember_token` varchar(100) null, `created_at` timestamp null, `updated_at` timestamp null, `mail_id` varchar(16) null, `checked_out` tinyint(1) not null default '0', `is_group_admin` tinyint(1) not null default '0', `group_id` bigint unsigned null, unique `users_email_unique`(`email`)) default character set utf8mb4 collate 'utf8mb4_unicode_ci';
CREATE TABLE IF NOT EXISTS `password_reset_tokens` (`email` varchar(255) not null, `token` varchar(255) not null, `created_at` timestamp null, primary key (`email`)) default character set utf8mb4 collate 'utf8mb4_unicode_ci';
CREATE TABLE IF NOT EXISTS `cache` (`key` varchar(255) not null, `value` mediumtext not null, `expiration` bigint not null, primary key (`key`), index `cache_expiration_index`(`expiration`)) default character set utf8mb4 collate 'utf8mb4_unicode_ci';
CREATE TABLE IF NOT EXISTS `cache_locks` (`key` varchar(255) not null, `owner` varchar(255) not null, `expiration` bigint not null, primary key (`key`), index `cache_locks_expiration_index`(`expiration`)) default character set utf8mb4 collate 'utf8mb4_unicode_ci';
CREATE TABLE IF NOT EXISTS `jobs` (`id` bigint unsigned not null auto_increment primary key, `queue` varchar(255) not null, `payload` longtext not null, `attempts` smallint unsigned not null, `reserved_at` int unsigned null, `available_at` int unsigned not null, `created_at` int unsigned not null, index `jobs_queue_index`(`queue`)) default character set utf8mb4 collate 'utf8mb4_unicode_ci';
CREATE TABLE IF NOT EXISTS `job_batches` (`id` varchar(255) not null, `name` varchar(255) not null, `total_jobs` int not null, `pending_jobs` int not null, `failed_jobs` int not null, `failed_job_ids` longtext not null, `options` mediumtext null, `cancelled_at` int null, `created_at` int not null, `finished_at` int null, primary key (`id`)) default character set utf8mb4 collate 'utf8mb4_unicode_ci';
CREATE TABLE IF NOT EXISTS `failed_jobs` (`id` bigint unsigned not null auto_increment primary key, `uuid` varchar(255) not null, `connection` varchar(255) not null, `queue` varchar(255) not null, `payload` longtext not null, `exception` longtext not null, `failed_at` timestamp not null default CURRENT_TIMESTAMP, index `failed_jobs_connection_queue_failed_at_index`(`connection`, `queue`, `failed_at`), unique `failed_jobs_uuid_unique`(`uuid`)) default character set utf8mb4 collate 'utf8mb4_unicode_ci';
CREATE TABLE IF NOT EXISTS `registration_groups` (`id` bigint unsigned not null auto_increment primary key, `name` varchar(255) not null, `checked_out` tinyint(1) not null default '0', `created_at` timestamp null, `updated_at` timestamp null, `is_group` tinyint(1) not null default '0') default character set utf8mb4 collate 'utf8mb4_unicode_ci';
CREATE TABLE IF NOT EXISTS `registration_currencies` (`code` varchar(3) not null, `name` varchar(255) not null, `symbol` varchar(255) not null, `rate` decimal(12, 8) not null, `def` tinyint(1) not null default '0', primary key (`code`), `enabled` tinyint(1) not null default '1') default character set utf8mb4 collate 'utf8mb4_unicode_ci';
CREATE TABLE IF NOT EXISTS `registration_sections` (`id` bigint unsigned not null auto_increment primary key, `scope` enum('participant', 'group') not null default 'participant', `key` varchar(255) not null, `title` varchar(255) not null, `description` text null, `position` int unsigned not null default '0', `enabled` tinyint(1) not null default '1', `created_at` timestamp null, `updated_at` timestamp null, unique `registration_sections_scope_key_unique`(`scope`, `key`), index `registration_sections_scope_position_index`(`scope`, `position`)) default character set utf8mb4 collate 'utf8mb4_unicode_ci';
CREATE TABLE IF NOT EXISTS `registration_questions` (`id` bigint unsigned not null auto_increment primary key, `section_id` bigint unsigned not null, `key` varchar(255) not null, `type` enum('text', 'textarea', 'email', 'tel', 'url', 'number', 'date', 'boolean', 'select', 'radio', 'checkbox', 'discount_code') not null default 'text', `label` varchar(255) not null, `help_text` text null, `placeholder` varchar(255) null, `required` tinyint(1) not null default '0', `position` int unsigned not null default '0', `config` json null, `enabled` tinyint(1) not null default '1', `created_at` timestamp null, `updated_at` timestamp null, constraint `registration_questions_section_id_foreign` foreign key (`section_id`) references `registration_sections` (`id`) on delete cascade, index `registration_questions_section_id_position_index`(`section_id`, `position`), index `registration_questions_key_index`(`key`)) default character set utf8mb4 collate 'utf8mb4_unicode_ci';
CREATE TABLE IF NOT EXISTS `registration_question_options` (`id` bigint unsigned not null auto_increment primary key, `question_id` bigint unsigned not null, `value` varchar(255) not null, `label` varchar(255) not null, `description` text null, `cost` decimal(8, 2) null, `position` int unsigned not null default '0', `is_default` tinyint(1) not null default '0', `created_at` timestamp null, `updated_at` timestamp null, constraint `registration_question_options_question_id_foreign` foreign key (`question_id`) references `registration_questions` (`id`) on delete cascade, index `registration_question_options_question_id_position_index`(`question_id`, `position`)) default character set utf8mb4 collate 'utf8mb4_unicode_ci';
CREATE TABLE IF NOT EXISTS `registration_answers` (`id` bigint unsigned not null auto_increment primary key, `question_id` bigint unsigned not null, `owner_type` varchar(255) not null, `owner_id` bigint unsigned not null, `option_id` bigint unsigned null, `value` text null, `created_at` timestamp null, `updated_at` timestamp null, constraint `registration_answers_question_id_foreign` foreign key (`question_id`) references `registration_questions` (`id`) on delete cascade, constraint `registration_answers_option_id_foreign` foreign key (`option_id`) references `registration_question_options` (`id`) on delete set null, index `registration_answers_owner_type_owner_id_index`(`owner_type`, `owner_id`), index `registration_answers_question_id_index`(`question_id`)) default character set utf8mb4 collate 'utf8mb4_unicode_ci';
CREATE TABLE IF NOT EXISTS `registration_condition_groups` (`id` bigint unsigned not null auto_increment primary key, `conditionable_type` varchar(255) null, `conditionable_id` bigint unsigned null, `parent_group_id` bigint unsigned null, `operator` enum('and', 'or') not null default 'and', `position` int unsigned not null default '0', `created_at` timestamp null, `updated_at` timestamp null, constraint `registration_condition_groups_parent_group_id_foreign` foreign key (`parent_group_id`) references `registration_condition_groups` (`id`) on delete cascade, index `registration_condition_groups_conditionable_index`(`conditionable_type`, `conditionable_id`)) default character set utf8mb4 collate 'utf8mb4_unicode_ci';
CREATE TABLE IF NOT EXISTS `registration_conditions` (`id` bigint unsigned not null auto_increment primary key, `condition_group_id` bigint unsigned not null, `question_id` bigint unsigned not null, `operator` enum('equals', 'not_equals', 'in', 'not_in', 'contains', 'is_answered', 'is_not_answered', 'greater_than', 'less_than') not null default 'equals', `value` text null, `position` int unsigned not null default '0', `created_at` timestamp null, `updated_at` timestamp null, constraint `registration_conditions_condition_group_id_foreign` foreign key (`condition_group_id`) references `registration_condition_groups` (`id`) on delete cascade, constraint `registration_conditions_question_id_foreign` foreign key (`question_id`) references `registration_questions` (`id`) on delete cascade, index `registration_conditions_condition_group_id_index`(`condition_group_id`)) default character set utf8mb4 collate 'utf8mb4_unicode_ci';
CREATE TABLE IF NOT EXISTS `registration_drafts` (`id` bigint unsigned not null auto_increment primary key, `user_id` bigint unsigned not null, `current_section_id` bigint unsigned null, `answers` json null, `created_at` timestamp null, `updated_at` timestamp null, `is_group` tinyint(1) null, constraint `registration_drafts_current_section_id_foreign` foreign key (`current_section_id`) references `registration_sections` (`id`) on delete set null, unique `registration_drafts_user_id_unique`(`user_id`)) default character set utf8mb4 collate 'utf8mb4_unicode_ci';
CREATE TABLE IF NOT EXISTS `passkeys` (`id` bigint unsigned not null auto_increment primary key, `user_id` bigint unsigned not null, `name` varchar(255) not null, `credential_id` varchar(255) not null, `credential` json not null, `last_used_at` timestamp null, `created_at` timestamp null, `updated_at` timestamp null, constraint `passkeys_user_id_foreign` foreign key (`user_id`) references `users` (`id`) on delete cascade, index `passkeys_user_id_index`(`user_id`), unique `passkeys_credential_id_unique`(`credential_id`)) default character set utf8mb4 collate 'utf8mb4_unicode_ci';
CREATE TABLE IF NOT EXISTS `settings` (`id` bigint unsigned not null auto_increment primary key, `key` varchar(255) not null, `value` longtext null, `created_at` timestamp null, `updated_at` timestamp null, unique `settings_key_unique`(`key`)) default character set utf8mb4 collate 'utf8mb4_unicode_ci';
CREATE TABLE IF NOT EXISTS `bof_phase_settings` (`id` bigint unsigned not null auto_increment primary key, `automatic_phase_changes_enabled` tinyint(1) not null default '0', `manual_phase_override` varchar(255) null, `timezone` varchar(255) not null default 'UTC', `nomination_starts_at` timestamp null, `selection_starts_at` timestamp null, `results_starts_at` timestamp null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci';
CREATE TABLE IF NOT EXISTS `bof_rooms` (`id` bigint unsigned not null auto_increment primary key, `name` varchar(255) not null, `size_weight` int unsigned not null default '50', `sort_order` int not null default '0', `is_active` tinyint(1) not null default '1', `is_special` tinyint(1) not null default '0', `created_at` timestamp null, `updated_at` timestamp null, index `bof_rooms_is_active_is_special_index`(`is_active`, `is_special`)) default character set utf8mb4 collate 'utf8mb4_unicode_ci';
CREATE TABLE IF NOT EXISTS `bof_time_slots` (`id` bigint unsigned not null auto_increment primary key, `starts_at` timestamp not null, `ends_at` timestamp not null, `display_label` varchar(255) null, `sort_order` int not null default '0', `is_active` tinyint(1) not null default '1', `is_special` tinyint(1) not null default '0', `created_at` timestamp null, `updated_at` timestamp null, index `bof_time_slots_is_active_is_special_index`(`is_active`, `is_special`)) default character set utf8mb4 collate 'utf8mb4_unicode_ci';
CREATE TABLE IF NOT EXISTS `bof_archives` (`id` bigint unsigned not null auto_increment primary key, `year` smallint unsigned not null, `slug` varchar(255) null, `name` varchar(255) not null, `archived_at` timestamp not null, `created_by_user_id` bigint unsigned null, `created_at` timestamp null, `updated_at` timestamp null, index `bof_archives_created_by_user_id_index`(`created_by_user_id`)) default character set utf8mb4 collate 'utf8mb4_unicode_ci';
CREATE TABLE IF NOT EXISTS `bof_sessions` (`id` bigint unsigned not null auto_increment primary key, `title` varchar(255) not null, `description` text null, `original_title` varchar(255) null, `original_description` text null, `submitted_by_user_id` bigint unsigned null, `submitter_display_name` varchar(255) null, `is_permanent` tinyint(1) not null default '0', `is_selected` tinyint(1) not null default '0', `status` varchar(255) not null default 'active', `facilitators` varchar(255) null, `merged_into_session_id` bigint unsigned null, `archive_id` bigint unsigned null, `archived_at` timestamp null, `deleted_at` timestamp null, `created_at` timestamp null, `updated_at` timestamp null, constraint `bof_sessions_merged_into_session_id_foreign` foreign key (`merged_into_session_id`) references `bof_sessions` (`id`) on delete set null, constraint `bof_sessions_archive_id_foreign` foreign key (`archive_id`) references `bof_archives` (`id`) on delete set null, index `bof_sessions_submitted_by_user_id_index`(`submitted_by_user_id`), index `bof_sessions_is_permanent_is_selected_index`(`is_permanent`, `is_selected`), index `bof_sessions_status_index`(`status`), index `bof_sessions_archive_id_index`(`archive_id`)) default character set utf8mb4 collate 'utf8mb4_unicode_ci';
CREATE TABLE IF NOT EXISTS `bof_session_merge_records` (`id` bigint unsigned not null auto_increment primary key, `primary_session_id` bigint unsigned not null, `merged_session_id` bigint unsigned not null, `original_title` varchar(255) not null, `original_description` text null, `created_by_user_id` bigint unsigned null, `created_at` timestamp null, `updated_at` timestamp null, constraint `bof_session_merge_records_primary_session_id_foreign` foreign key (`primary_session_id`) references `bof_sessions` (`id`) on delete cascade, constraint `bof_session_merge_records_merged_session_id_foreign` foreign key (`merged_session_id`) references `bof_sessions` (`id`) on delete cascade, index `bof_session_merge_records_primary_session_id_index`(`primary_session_id`), index `bof_session_merge_records_merged_session_id_index`(`merged_session_id`)) default character set utf8mb4 collate 'utf8mb4_unicode_ci';
CREATE TABLE IF NOT EXISTS `bof_session_preferences` (`id` bigint unsigned not null auto_increment primary key, `user_id` bigint unsigned not null, `session_id` bigint unsigned not null, `would_attend` tinyint(1) not null default '0', `disappointed_to_miss` tinyint(1) not null default '0', `permanent_attendance_status` varchar(255) null, `archive_id` bigint unsigned null, `created_at` timestamp null, `updated_at` timestamp null, `willing_to_facilitate` tinyint(1) not null default '0', constraint `bof_session_preferences_session_id_foreign` foreign key (`session_id`) references `bof_sessions` (`id`) on delete cascade, constraint `bof_session_preferences_archive_id_foreign` foreign key (`archive_id`) references `bof_archives` (`id`) on delete set null, unique `bof_session_preferences_user_id_session_id_archive_id_unique`(`user_id`, `session_id`, `archive_id`), index `bof_session_preferences_user_id_index`(`user_id`), index `bof_session_preferences_session_id_index`(`session_id`), index `bof_session_preferences_archive_id_index`(`archive_id`)) default character set utf8mb4 collate 'utf8mb4_unicode_ci';
CREATE TABLE IF NOT EXISTS `bof_schedule_assignments` (`id` bigint unsigned not null auto_increment primary key, `session_id` bigint unsigned not null, `room_id` bigint unsigned null, `time_slot_id` bigint unsigned null, `special_room_name` varchar(255) null, `special_starts_at` timestamp null, `special_ends_at` timestamp null, `is_locked` tinyint(1) not null default '0', `created_at` timestamp null, `updated_at` timestamp null, constraint `bof_schedule_assignments_session_id_foreign` foreign key (`session_id`) references `bof_sessions` (`id`) on delete cascade, constraint `bof_schedule_assignments_room_id_foreign` foreign key (`room_id`) references `bof_rooms` (`id`) on delete set null, constraint `bof_schedule_assignments_time_slot_id_foreign` foreign key (`time_slot_id`) references `bof_time_slots` (`id`) on delete set null, index `bof_schedule_assignments_session_id_index`(`session_id`), index `bof_schedule_assignments_room_id_time_slot_id_index`(`room_id`, `time_slot_id`)) default character set utf8mb4 collate 'utf8mb4_unicode_ci';
CREATE TABLE IF NOT EXISTS `registration_base_charges` (`id` bigint unsigned not null auto_increment primary key, `created_at` timestamp null, `updated_at` timestamp null, `name` varchar(255) not null, `amount` decimal(10, 2) not null, `enabled` tinyint(1) not null default '1', `order` int unsigned not null default '0') default character set utf8mb4 collate 'utf8mb4_unicode_ci';
CREATE TABLE IF NOT EXISTS `registration_discount_codes` (`id` bigint unsigned not null auto_increment primary key, `created_at` timestamp null, `updated_at` timestamp null, `code` varchar(255) not null, `formula` varchar(255) not null, `description` varchar(255) null, `enabled` tinyint(1) not null default '1') default character set utf8mb4 collate 'utf8mb4_unicode_ci';

-- Applied migrations (batch 1).
INSERT INTO `migrations` (`migration`, `batch`) SELECT '0001_01_01_000000_create_users_table', 1 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM `migrations` WHERE `migration` = '0001_01_01_000000_create_users_table');
INSERT INTO `migrations` (`migration`, `batch`) SELECT '0001_01_01_000001_create_cache_table', 1 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM `migrations` WHERE `migration` = '0001_01_01_000001_create_cache_table');
INSERT INTO `migrations` (`migration`, `batch`) SELECT '0001_01_01_000002_create_jobs_table', 1 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM `migrations` WHERE `migration` = '0001_01_01_000002_create_jobs_table');
INSERT INTO `migrations` (`migration`, `batch`) SELECT '2019_10_07_071610_create_groups_table', 1 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM `migrations` WHERE `migration` = '2019_10_07_071610_create_groups_table');
INSERT INTO `migrations` (`migration`, `batch`) SELECT '2019_11_12_141442_create_currencies_table', 1 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM `migrations` WHERE `migration` = '2019_11_12_141442_create_currencies_table');
INSERT INTO `migrations` (`migration`, `batch`) SELECT '2019_12_31_000000_add_registration_fields_to_users_table', 1 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM `migrations` WHERE `migration` = '2019_12_31_000000_add_registration_fields_to_users_table');
INSERT INTO `migrations` (`migration`, `batch`) SELECT '2020_01_01_000000_create_registration_sections_table', 1 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM `migrations` WHERE `migration` = '2020_01_01_000000_create_registration_sections_table');
INSERT INTO `migrations` (`migration`, `batch`) SELECT '2020_01_01_000100_create_registration_questions_table', 1 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM `migrations` WHERE `migration` = '2020_01_01_000100_create_registration_questions_table');
INSERT INTO `migrations` (`migration`, `batch`) SELECT '2020_01_01_000200_create_registration_question_options_table', 1 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM `migrations` WHERE `migration` = '2020_01_01_000200_create_registration_question_options_table');
INSERT INTO `migrations` (`migration`, `batch`) SELECT '2020_01_01_000300_create_registration_answers_table', 1 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM `migrations` WHERE `migration` = '2020_01_01_000300_create_registration_answers_table');
INSERT INTO `migrations` (`migration`, `batch`) SELECT '2020_01_01_000400_create_registration_condition_groups_table', 1 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM `migrations` WHERE `migration` = '2020_01_01_000400_create_registration_condition_groups_table');
INSERT INTO `migrations` (`migration`, `batch`) SELECT '2020_01_01_000500_create_registration_conditions_table', 1 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM `migrations` WHERE `migration` = '2020_01_01_000500_create_registration_conditions_table');
INSERT INTO `migrations` (`migration`, `batch`) SELECT '2020_01_02_000000_create_registration_drafts_table', 1 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM `migrations` WHERE `migration` = '2020_01_02_000000_create_registration_drafts_table');
INSERT INTO `migrations` (`migration`, `batch`) SELECT '2026_06_13_122743_create_passkeys_table', 1 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM `migrations` WHERE `migration` = '2026_06_13_122743_create_passkeys_table');
INSERT INTO `migrations` (`migration`, `batch`) SELECT '2026_06_13_130001_create_settings_table', 1 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM `migrations` WHERE `migration` = '2026_06_13_130001_create_settings_table');
INSERT INTO `migrations` (`migration`, `batch`) SELECT '2026_06_13_130002_create_phase_settings_table', 1 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM `migrations` WHERE `migration` = '2026_06_13_130002_create_phase_settings_table');
INSERT INTO `migrations` (`migration`, `batch`) SELECT '2026_06_13_130003_create_rooms_table', 1 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM `migrations` WHERE `migration` = '2026_06_13_130003_create_rooms_table');
INSERT INTO `migrations` (`migration`, `batch`) SELECT '2026_06_13_130004_create_time_slots_table', 1 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM `migrations` WHERE `migration` = '2026_06_13_130004_create_time_slots_table');
INSERT INTO `migrations` (`migration`, `batch`) SELECT '2026_06_13_130005_create_archives_table', 1 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM `migrations` WHERE `migration` = '2026_06_13_130005_create_archives_table');
INSERT INTO `migrations` (`migration`, `batch`) SELECT '2026_06_13_130006_create_sessions_table', 1 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM `migrations` WHERE `migration` = '2026_06_13_130006_create_sessions_table');
INSERT INTO `migrations` (`migration`, `batch`) SELECT '2026_06_13_130007_create_session_merge_records_table', 1 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM `migrations` WHERE `migration` = '2026_06_13_130007_create_session_merge_records_table');
INSERT INTO `migrations` (`migration`, `batch`) SELECT '2026_06_13_130008_create_session_preferences_table', 1 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM `migrations` WHERE `migration` = '2026_06_13_130008_create_session_preferences_table');
INSERT INTO `migrations` (`migration`, `batch`) SELECT '2026_06_13_130009_create_schedule_assignments_table', 1 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM `migrations` WHERE `migration` = '2026_06_13_130009_create_schedule_assignments_table');
INSERT INTO `migrations` (`migration`, `batch`) SELECT '2026_06_14_000001_add_willing_to_facilitate_to_session_preferences', 1 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM `migrations` WHERE `migration` = '2026_06_14_000001_add_willing_to_facilitate_to_session_preferences');
INSERT INTO `migrations` (`migration`, `batch`) SELECT '2026_06_22_000100_add_enabled_to_currencies_table', 1 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM `migrations` WHERE `migration` = '2026_06_22_000100_add_enabled_to_currencies_table');
INSERT INTO `migrations` (`migration`, `batch`) SELECT '2026_06_22_000300_create_base_charges_table', 1 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM `migrations` WHERE `migration` = '2026_06_22_000300_create_base_charges_table');
INSERT INTO `migrations` (`migration`, `batch`) SELECT '2026_06_22_000400_create_discount_codes_table', 1 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM `migrations` WHERE `migration` = '2026_06_22_000400_create_discount_codes_table');
INSERT INTO `migrations` (`migration`, `batch`) SELECT '2026_06_22_000500_add_is_group_to_groups_table', 1 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM `migrations` WHERE `migration` = '2026_06_22_000500_add_is_group_to_groups_table');
INSERT INTO `migrations` (`migration`, `batch`) SELECT '2026_06_22_000600_add_is_group_to_drafts_table', 1 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM `migrations` WHERE `migration` = '2026_06_22_000600_add_is_group_to_drafts_table');
SET FOREIGN_KEY_CHECKS=1;
